repos:
  - repo: local
    hooks:
      - id: draw-all
        name: Draw keymaps
        entry: just draw-all
        language: system
        always_run: true
        pass_filenames: false
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    - id: trailing-whitespace
      exclude: ^docs/generated/
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-json
