#define SELECT_WORD_OS_MAC

#define LUMINO_NO_EEPROM

// #define PALETTEFX_RIPPLE_ENABLE
#define PALETTEFX_REACTIVE_ENABLE

#define PALETTEFX_DRACULA_ENABLE
#define PALETTEFX_GROOVY_ENABLE
#define PALETTEFX_SPORT_ENABLE
#define PALETTEFX_NOTPINK_ENABLE
